spring:
    application:
        name: SpringSecurityTest
    mvc:
        static-path-pattern: /static/**
        log-resolved-exception: true
        converters:
            preferred-json-mapper: gson
    thymeleaf:
        mode: HTML
        encoding: utf-8
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    web:
        resources:
            static-locations:
                - classpath:/static/
            cache:
                period: 0
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
    output:
        ansi:
            enabled: always
server:
    tomcat:
        basedir: .
        remoteip:
            remote-ip-header: X-Forwarded-For
            protocol-header: framework
    error:
        include-exception: false
        include-stacktrace: never
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: mybatis-mapper/**/*.xml