spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;Mode=Oracle;DB_CLOSE_DELAY=-1
        username: sa
        password:
    devtools:
        livereload:
            enabled: true
    freemarker:
        cache: false
logging:
    config: classpath:logback/logback-local.xml
server:
    port: 8080
    servlet:
        context-path: /
ajp-config:
    address: 0.0.0.0
    port: 8015
